let russian = {
  inGameMessages: [
    'ходит',
    'взял карты',
    'отбил карты',
    'Сейчас не ваша очередь',
    'Взять',
    'Бито',
    'Ждем других игроков',
    'Готовы?',
    'проиграл',
    'Есть еще карты? Подкидывай',
  ],
  logInPage: ['Придумай псевдоним', 'Крутой псевдоним', 'Войти в лобби'],
  lobbyPage: [
    'Выйти',
    'Игроков в сети:',
    'Общий чат',
    'Отправить',
    'Сообщение в общий чат',
    'Доступные комнаты',
    'Создать комнату',
    'Настройки игровой комнаты',
    'название комнаты',
    'Количество игроков',
    'Количество карт',
    'Доступ',
    'Открытая',
    'Закрытая',
    'установите пароль',
    'Создать',
    'Название комнаты',
    'Кол-во карт',
    'Кол-во игроков',
    'Присоединится',
  ],
};

let english = {
  inGameMessages: [
    'turn',
    'took cards',
    'discarded cards',
    'It is not your turn now',
    'Take',
    'Discard',
    'Waiting for other players',
    'Ready?',
    'lost',
    'Have cards to give? Go ahead',
  ],
  logInPage: ['Create a Nick Name', 'Awesome nickname', 'Join Lobby'],
  lobbyPage: [
    'Sign out',
    'Players currently online: ',
    'Global Chat',
    'Send',
    'Message to the chat',
    'Available Rooms',
    'Create Room',
    'Choose Room Settings',
    'room name',
    'Players',
    'Cards',
    'Access',
    'Private',
    'Public',
    'set password',
    'Create',
    'Room name',
    'Number of Cards',
    'Players',
    'Join',
  ],
  warning: 'Your current browser is not supported. Please choose another one',
};

module.exports = { russian, english };
